import json, urllib.request

script = r"""
cb = me.parent().op('script1_callbacks')
t = chr(9)
nl = chr(10)
q = chr(34)

lines = []
lines.append('# DNA Multi-Pattern Cue Timeline Sequencer')
lines.append('')
lines.append('import json as _json')
lines.append('')
lines.append('def onSetupParameters(scriptOp):')
lines.append(t + 'pass')
lines.append('')
lines.append('def onCook(scriptOp):')
lines.append(t + 'scriptOp.clear()')
lines.append(t + 'ctrl = scriptOp.parent()')
lines.append(t + 'total_dur = ctrl.par.Totaldur.eval()')
lines.append(t + 'if total_dur <= 0:')
lines.append(t + t + 'total_dur = 1.0')
lines.append(t + 'frac = scriptOp.inputs[0][' + q + 'timer_fraction' + q + '].eval()')
lines.append(t + 'elapsed = frac * total_dur')
lines.append(t + 'first_ch = int(ctrl.par.Firstchan.eval())')
lines.append(t + 'total_ch = int(ctrl.par.Totalchans.eval())')
lines.append(t + '# Read disabled channels')
lines.append(t + 'dis_tbl = ctrl.op(' + q + 'disabled_chans' + q + ')')
lines.append(t + 'disabled = set()')
lines.append(t + 'if dis_tbl and dis_tbl.numRows >= 2:')
lines.append(t + t + 'for r in range(1, dis_tbl.numRows):')
lines.append(t + t + t + 'disabled.add(int(dis_tbl[r, ' + q + 'chan' + q + '].val))')
lines.append(t + '# Init all channels to 0')
lines.append(t + 'chan_vals = {}')
lines.append(t + 'for c in range(total_ch):')
lines.append(t + t + 'chan_vals[' + q + 'chan' + q + ' + str(first_ch + c)] = 0.0')
lines.append(t + '# Read cue timeline')
lines.append(t + 'cue_tl = ctrl.op(' + q + 'cue_timeline' + q + ')')
lines.append(t + 'cues_tbl = ctrl.op(' + q + 'cues' + q + ')')
lines.append(t + 'patterns_tbl = ctrl.op(' + q + 'patterns' + q + ')')
lines.append(t + 'all_patterns = []')
lines.append(t + '# From cue_timeline: each row is a cue placed at a time')
lines.append(t + 'if cue_tl and cue_tl.numRows >= 2 and cues_tbl and cues_tbl.numRows >= 2:')
lines.append(t + t + 'for row in range(1, cue_tl.numRows):')
lines.append(t + t + t + 'cue_name = cue_tl[row, ' + q + 'cue_name' + q + '].val')
lines.append(t + t + t + 'cue_start = float(cue_tl[row, ' + q + 'start_s' + q + '].val)')
lines.append(t + t + t + 'for cr in range(1, cues_tbl.numRows):')
lines.append(t + t + t + t + 'if cues_tbl[cr, ' + q + 'name' + q + '].val == cue_name:')
lines.append(t + t + t + t + t + 'try:')
lines.append(t + t + t + t + t + t + 'pats = _json.loads(cues_tbl[cr, ' + q + 'patterns_json' + q + '].val)')
lines.append(t + t + t + t + t + t + 'for p in pats:')
lines.append(t + t + t + t + t + t + t + 'all_patterns.append({')
lines.append(t + t + t + t + t + t + t + t + q + 'start' + q + ': p[' + q + 'start' + q + '] + cue_start,')
lines.append(t + t + t + t + t + t + t + t + q + 'ramp_up' + q + ': p[' + q + 'ramp_up' + q + '],')
lines.append(t + t + t + t + t + t + t + t + q + 'hold_high' + q + ': p[' + q + 'hold_high' + q + '],')
lines.append(t + t + t + t + t + t + t + t + q + 'ramp_down' + q + ': p[' + q + 'ramp_down' + q + '],')
lines.append(t + t + t + t + t + t + t + t + q + 'hold_low' + q + ': p[' + q + 'hold_low' + q + '],')
lines.append(t + t + t + t + t + t + t + t + q + 'start_ch' + q + ': p[' + q + 'start_chan' + q + '],')
lines.append(t + t + t + t + t + t + t + t + q + 'num_ch' + q + ': p[' + q + 'num_chans' + q + '],')
lines.append(t + t + t + t + t + t + t + t + q + 'delay_s' + q + ': p[' + q + 'delay_ms' + q + '] / 1000.0,')
lines.append(t + t + t + t + t + t + t + '})')
lines.append(t + t + t + t + t + 'except:')
lines.append(t + t + t + t + t + t + 'pass')
lines.append(t + t + t + t + t + 'break')
lines.append(t + '# Fallback: read direct patterns table')
lines.append(t + 'if len(all_patterns) == 0 and patterns_tbl and patterns_tbl.numRows >= 2:')
lines.append(t + t + 'for row in range(1, patterns_tbl.numRows):')
lines.append(t + t + t + 'all_patterns.append({')
lines.append(t + t + t + t + q + 'start' + q + ': float(patterns_tbl[row, ' + q + 'start_s' + q + '].val),')
lines.append(t + t + t + t + q + 'ramp_up' + q + ': float(patterns_tbl[row, ' + q + 'ramp_up' + q + '].val),')
lines.append(t + t + t + t + q + 'hold_high' + q + ': float(patterns_tbl[row, ' + q + 'hold_high' + q + '].val),')
lines.append(t + t + t + t + q + 'ramp_down' + q + ': float(patterns_tbl[row, ' + q + 'ramp_down' + q + '].val),')
lines.append(t + t + t + t + q + 'hold_low' + q + ': float(patterns_tbl[row, ' + q + 'hold_low' + q + '].val),')
lines.append(t + t + t + t + q + 'start_ch' + q + ': int(patterns_tbl[row, ' + q + 'start_chan' + q + '].val),')
lines.append(t + t + t + t + q + 'num_ch' + q + ': int(patterns_tbl[row, ' + q + 'num_chans' + q + '].val),')
lines.append(t + t + t + t + q + 'delay_s' + q + ': float(patterns_tbl[row, ' + q + 'delay_ms' + q + '].val) / 1000.0,')
lines.append(t + t + t + '})')
lines.append(t + '# Compute pattern values')
lines.append(t + 'for p in all_patterns:')
lines.append(t + t + 'wave_dur = p[' + q + 'ramp_up' + q + '] + p[' + q + 'hold_high' + q + '] + p[' + q + 'ramp_down' + q + '] + p[' + q + 'hold_low' + q + ']')
lines.append(t + t + 'for i in range(p[' + q + 'num_ch' + q + ']):')
lines.append(t + t + t + 'ch_num = p[' + q + 'start_ch' + q + '] + i')
lines.append(t + t + t + 'ch_name = ' + q + 'chan' + q + ' + str(ch_num)')
lines.append(t + t + t + '# Skip disabled channels')
lines.append(t + t + t + 'if ch_num in disabled:')
lines.append(t + t + t + t + 'if ch_name not in chan_vals:')
lines.append(t + t + t + t + t + 'chan_vals[ch_name] = 0.0')
lines.append(t + t + t + t + 'continue')
lines.append(t + t + t + 'ch_offset = p[' + q + 'start' + q + '] + i * p[' + q + 'delay_s' + q + ']')
lines.append(t + t + t + 'ch_elapsed = elapsed - ch_offset')
lines.append(t + t + t + 'if ch_elapsed <= 0 or wave_dur <= 0:')
lines.append(t + t + t + t + 'v = 0.0')
lines.append(t + t + t + 'elif ch_elapsed >= wave_dur:')
lines.append(t + t + t + t + 'v = 0.0')
lines.append(t + t + t + 'elif ch_elapsed <= p[' + q + 'ramp_up' + q + ']:')
lines.append(t + t + t + t + 'v = ch_elapsed / p[' + q + 'ramp_up' + q + '] if p[' + q + 'ramp_up' + q + '] > 0 else 1.0')
lines.append(t + t + t + 'elif ch_elapsed <= p[' + q + 'ramp_up' + q + '] + p[' + q + 'hold_high' + q + ']:')
lines.append(t + t + t + t + 'v = 1.0')
lines.append(t + t + t + 'elif ch_elapsed <= p[' + q + 'ramp_up' + q + '] + p[' + q + 'hold_high' + q + '] + p[' + q + 'ramp_down' + q + ']:')
lines.append(t + t + t + t + 'v = 1.0 - (ch_elapsed - p[' + q + 'ramp_up' + q + '] - p[' + q + 'hold_high' + q + ']) / p[' + q + 'ramp_down' + q + '] if p[' + q + 'ramp_down' + q + '] > 0 else 0.0')
lines.append(t + t + t + 'else:')
lines.append(t + t + t + t + 'v = 0.0')
lines.append(t + t + t + 'v = max(0.0, min(1.0, v))')
lines.append(t + t + t + 'if ch_name in chan_vals:')
lines.append(t + t + t + t + 'chan_vals[ch_name] = max(chan_vals[ch_name], v)')
lines.append(t + t + t + 'else:')
lines.append(t + t + t + t + 'chan_vals[ch_name] = v')
lines.append(t + '# Force disabled channels to 0')
lines.append(t + 'for ch_num in disabled:')
lines.append(t + t + 'ch_name = ' + q + 'chan' + q + ' + str(ch_num)')
lines.append(t + t + 'if ch_name in chan_vals:')
lines.append(t + t + t + 'chan_vals[ch_name] = 0.0')
lines.append(t + '# Output all channels')
lines.append(t + 'for ch_name in sorted(chan_vals.keys(), key=lambda x: int(x.replace(' + q + 'chan' + q + ',' + q + q + '))):')
lines.append(t + t + 'chan = scriptOp.appendChan(ch_name)')
lines.append(t + t + 'chan[0] = chan_vals[ch_name]')

cb.text = nl.join(lines)
result = 'Updated script1_callbacks with disabled channels support'
"""

data = json.dumps({'script': script}).encode()
req = urllib.request.Request('http://localhost:9981/api/exec', data=data, headers={'Content-Type':'application/json'})
resp = urllib.request.urlopen(req)
print(resp.read().decode())
